---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'yes'
static_data: ''
polling_verb: get
framework_version: 3.1.1
serverless_language: python
polling_url: https://trmnl.com/custom_plugin_example_data.json
polling_headers: Authorization=None
polling_body: "{}"
id: 318970
custom_fields:
- keyname: google_health
  name: Google Health (Fitbit)
  category: personal,sports
  field_type: author_bio
  description: Displays your daily activity and recovery metrics from Google Health. Note because this is an open-source plugin and I do not own the trmnl.com domain, I haven't gone through the formal process of getting the app verified by Google. So you will see an 'Unverified App' warning when connecting your google account. This is normal and can be bypassed. The code for this plugin is on github. Hope you enjoy it!
  github_url: https://github.com/dsdilpreet/trmnl-plugins
name: Google Health
refresh_interval: 15
